services:
  nginx:
    image: 'nginx:alpine-slim'
    expose:
      - '80'
    volumes:
      - ..:/var/www
      - ./logs/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /var/www
    networks:
      - skipper_network
      - default

  php-fpm:
    build:
      context: ./php-fpm
    expose:
      - '9000'
    volumes:
      - ../:/var/www

  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpsw
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
      - 3306
    ports:
      - ${MAC_DB_PORT}:3306

  # postgres:
  #     image: "postgres:15-alpine"
  #     environment:
  #         POSTGRES_DB: dbname
  #         POSTGRES_USER: dbuser
  #         POSTGRES_PASSWORD: dbpsw
  #     volumes:
  #         - postgres:/var/lib/postgresql/data
  #     expose:
  #         - 5432
  #     ports:
  #         - ${MAC_DB_PORT}:5432

  # redis:
  #   image: 'redis:alpine'
  #   expose:
  #     - 6379
  #   volumes:
  #     - redis:/data # Remember to uncomment redis in the volumes section

networks:
  default:
    driver: bridge
  skipper_network:
    external: true

volumes:
  mysql:
    driver: 'local'
  # postgres:
  #   driver: "local"
  # redis:
  #   driver: "local"
